### PR TITLE
Fix decompiling encrypted 3.x scripts

### LINKED ISSUE #64: Nonexistent function 'set_key' in base 'PckDumper'
Version v0.0.9 will return this error when using the "key" argument and not decompile the scripts.

```
SCRIPT ERROR: Invalid call. Nonexistent function 'set_key' in base 'PckDumper'.
          at: dump_files (res://gdre_main.gd:64)
```

### PR DESCRIPTION
**Pull request by polybiusproxy**
Fixes #64.

### CODE REVIEW

**Comment by nikitalita** [comment]
Thanks for the PR! Can you try the artifact from the build action to verify that this worked?

**Comment by polybiusproxy** [comment]
> Thanks for the PR! Can you try the artifact from the build action to verify that this worked?

Of course! I will try once I'm free.

**Comment by polybiusproxy** [comment]
I can confirm the error is gone, however, the scripts (.gde files) didn't decompile.
Doing it manually on the UI will return this error: `Condition "p_base->get_length() < base + length" is true. Returning: ERR_FILE_CORRUPT`.

**Comment by nikitalita** [comment]
Does this error also occur if you use the `--recover` option in the CLI to recover the whole project?

**Comment by polybiusproxy** [comment]
> Does this error also occur if you use the `--recover` option in the CLI to recover the whole project?

Hey, sorry for replying late!
Both the CLI and the editor return the same error.

**Comment by nikitalita** [comment]
Are you able to share the game in question? If you want to do it privately, you can hit me up on the godot discord.

**Comment by nikitalita** [comment]
Thanks for the PR! I've added additional commits to fix the issue; I had to add back the v3 version of FileAccessEncrypted to decrypt files as V4 introduced breaking changes.

**Pull request merged**
